//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace POCO
{
    public partial class SafeDrivingEntities : ObjectContext
    {
        public const string ConnectionString = "name=SafeDrivingEntities";
        public const string ContainerName = "SafeDrivingEntities";
    
        #region Constructors
    
        public SafeDrivingEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public SafeDrivingEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public SafeDrivingEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Article> Articles
        {
            get { return _articles  ?? (_articles = CreateObjectSet<Article>("Articles")); }
        }
        private ObjectSet<Article> _articles;
    
        public ObjectSet<Circuit> Circuits
        {
            get { return _circuits  ?? (_circuits = CreateObjectSet<Circuit>("Circuits")); }
        }
        private ObjectSet<Circuit> _circuits;
    
        public ObjectSet<Offre> Offres
        {
            get { return _offres  ?? (_offres = CreateObjectSet<Offre>("Offres")); }
        }
        private ObjectSet<Offre> _offres;
    
        public ObjectSet<OffresReference> OffresReferences
        {
            get { return _offresReferences  ?? (_offresReferences = CreateObjectSet<OffresReference>("OffresReferences")); }
        }
        private ObjectSet<OffresReference> _offresReferences;
    
        public ObjectSet<Session> Sessions
        {
            get { return _sessions  ?? (_sessions = CreateObjectSet<Session>("Sessions")); }
        }
        private ObjectSet<Session> _sessions;
    
        public ObjectSet<Utilisateur> Utilisateurs
        {
            get { return _utilisateurs  ?? (_utilisateurs = CreateObjectSet<Utilisateur>("Utilisateurs")); }
        }
        private ObjectSet<Utilisateur> _utilisateurs;
    
        public ObjectSet<Vehicule> Vehicules
        {
            get { return _vehicules  ?? (_vehicules = CreateObjectSet<Vehicule>("Vehicules")); }
        }
        private ObjectSet<Vehicule> _vehicules;
    
        public ObjectSet<TypeSession> TypeSessions
        {
            get { return _typeSessions  ?? (_typeSessions = CreateObjectSet<TypeSession>("TypeSessions")); }
        }
        private ObjectSet<TypeSession> _typeSessions;
    
        public ObjectSet<Role> Roles
        {
            get { return _roles  ?? (_roles = CreateObjectSet<Role>("Roles")); }
        }
        private ObjectSet<Role> _roles;
    
        public ObjectSet<EtatSession> EtatSessions
        {
            get { return _etatSessions  ?? (_etatSessions = CreateObjectSet<EtatSession>("EtatSessions")); }
        }
        private ObjectSet<EtatSession> _etatSessions;
    
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get { return _sysdiagrams  ?? (_sysdiagrams = CreateObjectSet<sysdiagram>("sysdiagrams")); }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        public ObjectSet<OffresReferencesTypeSession> OffresReferencesTypeSessions
        {
            get { return _offresReferencesTypeSessions  ?? (_offresReferencesTypeSessions = CreateObjectSet<OffresReferencesTypeSession>("OffresReferencesTypeSessions")); }
        }
        private ObjectSet<OffresReferencesTypeSession> _offresReferencesTypeSessions;
    
        public ObjectSet<Utilisateurs_ClientSessions> Utilisateurs_ClientSessions
        {
            get { return _utilisateurs_ClientSessions  ?? (_utilisateurs_ClientSessions = CreateObjectSet<Utilisateurs_ClientSessions>("Utilisateurs_ClientSessions")); }
        }
        private ObjectSet<Utilisateurs_ClientSessions> _utilisateurs_ClientSessions;
    
        public ObjectSet<Categorie> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Categorie>("Categories")); }
        }
        private ObjectSet<Categorie> _categories;
    
        public ObjectSet<Message> Messages
        {
            get { return _messages  ?? (_messages = CreateObjectSet<Message>("Messages")); }
        }
        private ObjectSet<Message> _messages;
    
        public ObjectSet<Topic> Topics
        {
            get { return _topics  ?? (_topics = CreateObjectSet<Topic>("Topics")); }
        }
        private ObjectSet<Topic> _topics;
    
        public ObjectSet<TypeArticle> TypeArticles
        {
            get { return _typeArticles  ?? (_typeArticles = CreateObjectSet<TypeArticle>("TypeArticles")); }
        }
        private ObjectSet<TypeArticle> _typeArticles;

        #endregion
    }
}
