//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace POCO
{
    public partial class OffresReferencesSession
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int OffresReferencesId
        {
            get { return _offresReferencesId; }
            set
            {
                if (_offresReferencesId != value)
                {
                    if (OffresReference != null && OffresReference.Id != value)
                    {
                        OffresReference = null;
                    }
                    _offresReferencesId = value;
                }
            }
        }
        private int _offresReferencesId;
    
        public virtual int TypeSessions
        {
            get { return _typeSessions; }
            set
            {
                if (_typeSessions != value)
                {
                    if (TypeSession != null && TypeSession.Id != value)
                    {
                        TypeSession = null;
                    }
                    _typeSessions = value;
                }
            }
        }
        private int _typeSessions;

        #endregion
        #region Navigation Properties
    
        public virtual OffresReference OffresReference
        {
            get { return _offresReference; }
            set
            {
                if (!ReferenceEquals(_offresReference, value))
                {
                    var previousValue = _offresReference;
                    _offresReference = value;
                    FixupOffresReference(previousValue);
                }
            }
        }
        private OffresReference _offresReference;
    
        public virtual TypeSession TypeSession
        {
            get { return _typeSession; }
            set
            {
                if (!ReferenceEquals(_typeSession, value))
                {
                    var previousValue = _typeSession;
                    _typeSession = value;
                    FixupTypeSession(previousValue);
                }
            }
        }
        private TypeSession _typeSession;

        #endregion
        #region Association Fixup
    
        private void FixupOffresReference(OffresReference previousValue)
        {
            if (previousValue != null && previousValue.OffresReferencesSessions.Contains(this))
            {
                previousValue.OffresReferencesSessions.Remove(this);
            }
    
            if (OffresReference != null)
            {
                if (!OffresReference.OffresReferencesSessions.Contains(this))
                {
                    OffresReference.OffresReferencesSessions.Add(this);
                }
                if (OffresReferencesId != OffresReference.Id)
                {
                    OffresReferencesId = OffresReference.Id;
                }
            }
        }
    
        private void FixupTypeSession(TypeSession previousValue)
        {
            if (previousValue != null && previousValue.OffresReferencesSessions.Contains(this))
            {
                previousValue.OffresReferencesSessions.Remove(this);
            }
    
            if (TypeSession != null)
            {
                if (!TypeSession.OffresReferencesSessions.Contains(this))
                {
                    TypeSession.OffresReferencesSessions.Add(this);
                }
                if (TypeSessions != TypeSession.Id)
                {
                    TypeSessions = TypeSession.Id;
                }
            }
        }

        #endregion
    }
}
