//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace POCO
{
    public partial class OffreSession
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int OffreId
        {
            get { return _offreId; }
            set
            {
                if (_offreId != value)
                {
                    if (Offre != null && Offre.Id != value)
                    {
                        Offre = null;
                    }
                    _offreId = value;
                }
            }
        }
        private int _offreId;
    
        public virtual int SessionId
        {
            get { return _sessionId; }
            set
            {
                if (_sessionId != value)
                {
                    if (Session != null && Session.Id != value)
                    {
                        Session = null;
                    }
                    _sessionId = value;
                }
            }
        }
        private int _sessionId;
    
        public virtual float Note
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Offre Offre
        {
            get { return _offre; }
            set
            {
                if (!ReferenceEquals(_offre, value))
                {
                    var previousValue = _offre;
                    _offre = value;
                    FixupOffre(previousValue);
                }
            }
        }
        private Offre _offre;
    
        public virtual Session Session
        {
            get { return _session; }
            set
            {
                if (!ReferenceEquals(_session, value))
                {
                    var previousValue = _session;
                    _session = value;
                    FixupSession(previousValue);
                }
            }
        }
        private Session _session;

        #endregion
        #region Association Fixup
    
        private void FixupOffre(Offre previousValue)
        {
            if (previousValue != null && previousValue.OffreSessions.Contains(this))
            {
                previousValue.OffreSessions.Remove(this);
            }
    
            if (Offre != null)
            {
                if (!Offre.OffreSessions.Contains(this))
                {
                    Offre.OffreSessions.Add(this);
                }
                if (OffreId != Offre.Id)
                {
                    OffreId = Offre.Id;
                }
            }
        }
    
        private void FixupSession(Session previousValue)
        {
            if (previousValue != null && previousValue.OffreSessions.Contains(this))
            {
                previousValue.OffreSessions.Remove(this);
            }
    
            if (Session != null)
            {
                if (!Session.OffreSessions.Contains(this))
                {
                    Session.OffreSessions.Add(this);
                }
                if (SessionId != Session.Id)
                {
                    SessionId = Session.Id;
                }
            }
        }

        #endregion
    }
}
