//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace POCO
{
    public partial class OffresReferencesTypeSession
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int OffresReferencesId
        {
            get { return _offresReferencesId; }
            set
            {
                if (_offresReferencesId != value)
                {
                    if (OffresReference != null && OffresReference.Id != value)
                    {
                        OffresReference = null;
                    }
                    _offresReferencesId = value;
                }
            }
        }
        private int _offresReferencesId;
    
        public virtual int TypeSessionId
        {
            get;
            set;
        }
    
        public virtual int NbTypeSession
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual OffresReference OffresReference
        {
            get { return _offresReference; }
            set
            {
                if (!ReferenceEquals(_offresReference, value))
                {
                    var previousValue = _offresReference;
                    _offresReference = value;
                    FixupOffresReference(previousValue);
                }
            }
        }
        private OffresReference _offresReference;

        #endregion
        #region Association Fixup
    
        private void FixupOffresReference(OffresReference previousValue)
        {
            if (previousValue != null && previousValue.OffresReferencesTypeSessions.Contains(this))
            {
                previousValue.OffresReferencesTypeSessions.Remove(this);
            }
    
            if (OffresReference != null)
            {
                if (!OffresReference.OffresReferencesTypeSessions.Contains(this))
                {
                    OffresReference.OffresReferencesTypeSessions.Add(this);
                }
                if (OffresReferencesId != OffresReference.Id)
                {
                    OffresReferencesId = OffresReference.Id;
                }
            }
        }

        #endregion
    }
}
