//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace POCO
{
    public partial class Role
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Privilege
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Utilisateur> Utilisateurs
        {
            get
            {
                if (_utilisateurs == null)
                {
                    var newCollection = new FixupCollection<Utilisateur>();
                    newCollection.CollectionChanged += FixupUtilisateurs;
                    _utilisateurs = newCollection;
                }
                return _utilisateurs;
            }
            set
            {
                if (!ReferenceEquals(_utilisateurs, value))
                {
                    var previousValue = _utilisateurs as FixupCollection<Utilisateur>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUtilisateurs;
                    }
                    _utilisateurs = value;
                    var newValue = value as FixupCollection<Utilisateur>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUtilisateurs;
                    }
                }
            }
        }
        private ICollection<Utilisateur> _utilisateurs;

        #endregion
        #region Association Fixup
    
        private void FixupUtilisateurs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Utilisateur item in e.NewItems)
                {
                    item.Role = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Utilisateur item in e.OldItems)
                {
                    if (ReferenceEquals(item.Role, this))
                    {
                        item.Role = null;
                    }
                }
            }
        }

        #endregion
    }
}
