//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace POCO
{
    public partial class TypeArticle
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Nom
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Article> Articles
        {
            get
            {
                if (_articles == null)
                {
                    var newCollection = new FixupCollection<Article>();
                    newCollection.CollectionChanged += FixupArticles;
                    _articles = newCollection;
                }
                return _articles;
            }
            set
            {
                if (!ReferenceEquals(_articles, value))
                {
                    var previousValue = _articles as FixupCollection<Article>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupArticles;
                    }
                    _articles = value;
                    var newValue = value as FixupCollection<Article>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupArticles;
                    }
                }
            }
        }
        private ICollection<Article> _articles;

        #endregion
        #region Association Fixup
    
        private void FixupArticles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Article item in e.NewItems)
                {
                    item.TypeArticle = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Article item in e.OldItems)
                {
                    if (ReferenceEquals(item.TypeArticle, this))
                    {
                        item.TypeArticle = null;
                    }
                }
            }
        }

        #endregion
    }
}
