//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace POCO
{
    public partial class Utilisateur
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Nom
        {
            get;
            set;
        }
    
        public virtual string Prenom
        {
            get;
            set;
        }
    
        public virtual string Adresse
        {
            get;
            set;
        }
    
        public virtual string Ville
        {
            get;
            set;
        }
    
        public virtual string CodePostal
        {
            get;
            set;
        }
    
        public virtual string Telephone
        {
            get;
            set;
        }
    
        public virtual string Mail
        {
            get;
            set;
        }
    
        public virtual string Password
        {
            get;
            set;
        }
    
        public virtual int RoleId
        {
            get { return _roleId; }
            set
            {
                if (_roleId != value)
                {
                    if (Role != null && Role.Id != value)
                    {
                        Role = null;
                    }
                    _roleId = value;
                }
            }
        }
        private int _roleId;
    
        public virtual byte[] Avatar
        {
            get;
            set;
        }
    
        public virtual string Pseudo
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Role Role
        {
            get { return _role; }
            set
            {
                if (!ReferenceEquals(_role, value))
                {
                    var previousValue = _role;
                    _role = value;
                    FixupRole(previousValue);
                }
            }
        }
        private Role _role;

        #endregion
        #region Association Fixup
    
        private void FixupRole(Role previousValue)
        {
            if (previousValue != null && previousValue.Utilisateurs.Contains(this))
            {
                previousValue.Utilisateurs.Remove(this);
            }
    
            if (Role != null)
            {
                if (!Role.Utilisateurs.Contains(this))
                {
                    Role.Utilisateurs.Add(this);
                }
                if (RoleId != Role.Id)
                {
                    RoleId = Role.Id;
                }
            }
        }

        #endregion
    }
}
