//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace POCO
{
    public partial class Vehicule
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Nom
        {
            get;
            set;
        }
    
        public virtual int Sessions_id
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Session> Sessions
        {
            get
            {
                if (_sessions == null)
                {
                    var newCollection = new FixupCollection<Session>();
                    newCollection.CollectionChanged += FixupSessions;
                    _sessions = newCollection;
                }
                return _sessions;
            }
            set
            {
                if (!ReferenceEquals(_sessions, value))
                {
                    var previousValue = _sessions as FixupCollection<Session>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSessions;
                    }
                    _sessions = value;
                    var newValue = value as FixupCollection<Session>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSessions;
                    }
                }
            }
        }
        private ICollection<Session> _sessions;

        #endregion
        #region Association Fixup
    
        private void FixupSessions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Session item in e.NewItems)
                {
                    if (!item.Vehicules.Contains(this))
                    {
                        item.Vehicules.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Session item in e.OldItems)
                {
                    if (item.Vehicules.Contains(this))
                    {
                        item.Vehicules.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
